[package]
name = "rosm_pbf_sqlite_dumper"
version = "0.1.0"
authors = ["Zsolt Bölöny <bolony.zsolt@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rosm_pbf_reader = { path = "../rosm_pbf_reader" }
rusqlite = { version = "0.21.0", features = ["bundled"] }
